# Generated by Django 5.1.5 on 2025-01-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_rename_direccion_direcciones'),
        ('refugios', '0001_initial'),
        ('usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direcciones',
            new_name='Direccion',
        ),
    ]
