# Generated by Django 5.1.5 on 2025-01-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField(blank=True, null=True)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_mascota', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('estado_salud', models.CharField(blank=True, max_length=100, null=True)),
                ('id_refugio', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
