# Generated by Django 5.1.5 on 2025-01-28 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direcciones', '0001_initial'),
        ('usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refugios', to='direcciones.direccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refugios', to='usuarios.usuario')),
            ],
        ),
    ]
