# Generated by Django 5.1.5 on 2025-01-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_rename_direcciones_direccion'),
        ('refugios', '0001_initial'),
        ('usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refugios',
            new_name='Refugio',
        ),
    ]
