# Generated by Django 5.1.5 on 2025-02-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_rename_direcciones_direccion'),
        ('refugios', '0003_remove_refugio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refugios', to='direcciones.direccion'),
        ),
    ]
