# Generated by Django 5.1.5 on 2025-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADOPTANTE', 'Adoptante'), ('REFUGIO', 'Refugio')], max_length=50),
        ),
    ]
